/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.4

For download info, please visit:
http://www.lilacsoul.revility.com    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (!(GetGold(oPC) < 500)) return FALSE;

return TRUE;
}
