 /*   Script generated by
//Lilac Soul's NWN Script Generator, v. 2.3*/
// Script that check for Ulum-Ta's Heart on the PC
int StartingConditional()
{
object oPC = GetPCSpeaker();

if (GetItemPossessedBy(oPC, "mc_ulumheart") == OBJECT_INVALID) return FALSE;

return TRUE;
}

