// prc_onenter,onmodenter
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the oncliententer event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onenter", OBJECT_SELF);
    ExecuteScript("onmodenter", OBJECT_SELF);
}
