// prc_onunaquire,kh_onunacquire
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onunaquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onunaquire", OBJECT_SELF);
    ExecuteScript("kh_onunacquire", OBJECT_SELF);
}
