// prc_onmodload,moduleload
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onmoduleload event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onmodload", OBJECT_SELF);
    ExecuteScript("moduleload", OBJECT_SELF);
}
