// prc_unequip,cw_mod_unequip
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerunequipitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_unequip", OBJECT_SELF);
    ExecuteScript("cw_mod_unequip", OBJECT_SELF);
}
