object oDeny;
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

if (!ReflexSave(oPC, 60))
   {
   oDeny = GetWaypointByTag("pc_DeathJump");

   AssignCommand(oPC, JumpToObject(oDeny));

   return;
   }

FloatingTextStringOnCreature("You almost fell!!!", oPC);

}


