
//const int FEAT_WEAPON_FOCUS_WHIP      = 993;
//const int FEAT_IMPROVED_CRITICAL_WHIP = 995;

//iprp_feats

const int IP_CONST_FEAT_IMPROVED_CRITICAL_UNARMED  = 20;

const int IP_CONST_FEAT_SNEAKATK1     = 32;
const int IP_CONST_FEAT_SNEAKATK2     = 33;
const int IP_CONST_FEAT_SNEAKATK3     = 34;
const int IP_CONST_FEAT_SNEAKATK4     = 301;
const int IP_CONST_FEAT_SNEAKATK5     = 39;
const int IP_CONST_FEAT_SNEAKATK6     = 302;
const int IP_CONST_FEAT_SNEAKATK7     = 303;
const int IP_CONST_FEAT_SNEAKATK8     = 304;
const int IP_CONST_FEAT_SNEAKATK9     = 305;
const int IP_CONST_FEAT_SNEAKATK10    = 306;
const int IP_CONST_FEAT_SNEAKATK11    = 307;
const int IP_CONST_FEAT_SNEAKATK12    = 308;
const int IP_CONST_FEAT_SNEAKATK13    = 309;
const int IP_CONST_FEAT_SNEAKATK14    = 310;
const int IP_CONST_FEAT_SNEAKATK15    = 311;
const int IP_CONST_FEAT_SNEAKATK16    = 312;
const int IP_CONST_FEAT_SNEAKATK17    = 313;
const int IP_CONST_FEAT_SNEAKATK18    = 314;
const int IP_CONST_FEAT_SNEAKATK19    = 315;
const int IP_CONST_FEAT_SNEAKATK20    = 316;
const int IP_CONST_FEAT_DEATHATTACK   = 317;
const int IP_CONST_FEAT_DEATHATTACK2   = 318;
const int IP_CONST_FEAT_DEATHATTACK3   = 319;
const int IP_CONST_FEAT_DEATHATTACK4   = 320;
const int IP_CONST_FEAT_DEATHATTACK5   = 321;
const int IP_CONST_FEAT_DEATHATTACK6   = 322;
const int IP_CONST_FEAT_DEATHATTACK7   = 323;
const int IP_CONST_FEAT_DEATHATTACK8   = 324;
const int IP_CONST_FEAT_DEATHATTACK9   = 325;
const int IP_CONST_FEAT_DEATHATTACK10  = 326;
const int IP_CONST_FEAT_DEATHATTACK11  = 327;
const int IP_CONST_FEAT_DEATHATTACK12  = 328;
const int IP_CONST_FEAT_DEATHATTACK13  = 329;
const int IP_CONST_FEAT_DEATHATTACK14  = 330;
const int IP_CONST_FEAT_DEATHATTACK15  = 331;
const int IP_CONST_FEAT_DEATHATTACK16  = 332;
const int IP_CONST_FEAT_DEATHATTACK17  = 333;
const int IP_CONST_FEAT_DEATHATTACK18  = 334;
const int IP_CONST_FEAT_DEATHATTACK19  = 335;
const int IP_CONST_FEAT_DEATHATTACK20  = 336;
const int IP_CONST_FEAT_BarbEndurance  = 337;
const int IP_CONST_FEAT_WeapFocCreature      = 338;
const int IP_CONST_FEAT_ImpCritCreature      = 339;
const int IP_CONST_FEAT_WeapSpecCreature     = 340;
const int IP_CONST_FEAT_WeapEpicFocCreature  = 341;
const int IP_CONST_FEAT_WeapEpicSpecCreature = 342;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DAGGER  = 343;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DART  = 344;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HEAVY_CROSSBOW  = 345;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_CROSSBOW  = 346;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_MACE  = 347;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_MORNING_STAR  = 348;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_STAFF  = 349;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SPEAR  = 350;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SICKLE  = 351;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SLING  = 352;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LONGBOW  = 353;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SHORTBOW  = 354;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SHORT_SWORD = 355;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_RAPIER  = 356;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SCIMITAR  = 357;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LONG_SWORD  = 358;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_GREAT_SWORD  = 359;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HAND_AXE  = 360;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_THROWING_AXE  = 361;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_BATTLE_AXE  = 362;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_GREAT_AXE  = 363;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HALBERD  = 364;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_HAMMER  = 365;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_LIGHT_FLAIL  = 366;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_WAR_HAMMER  = 367;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_HEAVY_FLAIL  = 368;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_KAMA  = 369;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_KUKRI  = 370;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SHURIKEN  = 371;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_SCYTHE  = 372;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_KATANA  = 373;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_BASTARD_SWORD  = 374;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DIRE_MACE  = 375;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DOUBLE_AXE  = 376;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_TWO_BLADED_SWORD  = 377;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_CLUB  = 378;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_DWAXE  = 379;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_WHIP = 380;
const int IP_CONST_FEAT_IMPROVED_CRITICAL_MINDBLADE = 388;
const int IP_CONST_FEAT_SF_CODE = 381;
const int IP_CONST_FEAT_UNCANNY_DODGE1 = 382;
const int IP_CONST_FEAT_LOWLIGHT_VISION = 383;
const int IP_CONST_FEAT_NEW_PWATK = 384;
const int IP_CONST_FEAT_NEW_IPWATK = 385;
const int IP_CONST_FEAT_DARKVISION  = 391;

const int IP_CONST_FEAT_LIGHT_ARMOR_PROF        = 96;
const int IP_CONST_FEAT_HEAVY_ARMOR_PROF        = 95;
const int IP_CONST_FEAT_SHIELD_PROF             = 94;

const int IP_CONST_FEAT_EPIC_AUTO_STILL_I       = 204;
const int IP_CONST_FEAT_EPIC_AUTO_STILL_II      = 205;
const int IP_CONST_FEAT_EPIC_AUTO_STILL_III     = 206;
const int IP_CONST_FEAT_EPIC_AUTO_QUICKEN_I     = 207;
const int IP_CONST_FEAT_EPIC_AUTO_QUICKEN_II    = 208;
const int IP_CONST_FEAT_EPIC_AUTO_QUICKEN_III   = 209;
const int IP_CONST_FEAT_EPIC_AUTO_SILENT_I      = 210;
const int IP_CONST_FEAT_EPIC_AUTO_SILENT_II     = 211;
const int IP_CONST_FEAT_EPIC_AUTO_SILENT_III    = 212;


const int IP_CONST_FEAT_KI_STRIKE = 254;

const int IP_CONST_FEAT_REND            = 255;
const int IP_CONST_FEAT_SPELL10         = 256;
//const int IP_CONST_FEAT_MOBILITY        = 27; // Provided by Bioware in 1.66
//const int IP_CONST_FEAT_WHIRLWIND       = 29; // ------------||-------------
const int IP_CONST_FEAT_BLINDFIGHT      = 257;
const int IP_CONST_FEAT_SPRINGATTACK    = 258;
const int IP_CONST_FEAT_EVASION         = 386;
const int IP_CONST_FEAT_IMPEVASION      = 387;
const int IP_CONST_FEAT_GREAT_CLEAVE    = 260;
const int IP_CONST_FEAT_PSIONIC_FOCUS   = 259;
const int IP_CONST_FEAT_IMPROVED_INIT   = 261;

const int IP_CONST_FEAT_POWER_ATTACK_SINGLE_RADIAL     = 252;
const int IP_CONST_FEAT_POWER_ATTACK_FIVES_RADIAL      = 253;
const int IP_CONST_FEAT_PRC_POWER_ATTACK_QUICKS_RADIAL = 262;

const int IP_CONST_FEAT_TELEPORT_MANAGEMENT_RADIAL     = 263;

const int IP_CONST_FEAT_EPIC_REST                                   = 399;

const int IP_CONST_FEAT_WEAPON_FOCUS_CLUB                           = 100;
const int IP_CONST_FEAT_WEAPON_FOCUS_DAGGER                         = 101;
const int IP_CONST_FEAT_WEAPON_FOCUS_DART                           = 102;
const int IP_CONST_FEAT_WEAPON_FOCUS_HEAVY_CROSSBOW                 = 103;
const int IP_CONST_FEAT_WEAPON_FOCUS_LIGHT_CROSSBOW                 = 104;
const int IP_CONST_FEAT_WEAPON_FOCUS_LIGHT_MACE                     = 105;
const int IP_CONST_FEAT_WEAPON_FOCUS_MORNING_STAR                   = 106;
const int IP_CONST_FEAT_WEAPON_FOCUS_STAFF                          = 107;
const int IP_CONST_FEAT_WEAPON_FOCUS_SPEAR                          = 108;
const int IP_CONST_FEAT_WEAPON_FOCUS_SICKLE                         = 109;
const int IP_CONST_FEAT_WEAPON_FOCUS_SLING                          = 110;
const int IP_CONST_FEAT_WEAPON_FOCUS_UNARMED_STRIKE                 = 111;
const int IP_CONST_FEAT_WEAPON_FOCUS_LONGBOW                        = 112;
const int IP_CONST_FEAT_WEAPON_FOCUS_SHORTBOW                       = 113;
const int IP_CONST_FEAT_WEAPON_FOCUS_SHORT_SWORD                    = 114;
const int IP_CONST_FEAT_WEAPON_FOCUS_RAPIER                         = 115;
const int IP_CONST_FEAT_WEAPON_FOCUS_SCIMITAR                       = 116;
const int IP_CONST_FEAT_WEAPON_FOCUS_LONG_SWORD                     = 117;
const int IP_CONST_FEAT_WEAPON_FOCUS_GREAT_SWORD                    = 118;
const int IP_CONST_FEAT_WEAPON_FOCUS_HAND_AXE                       = 119;
const int IP_CONST_FEAT_WEAPON_FOCUS_THROWING_AXE                   = 120;
const int IP_CONST_FEAT_WEAPON_FOCUS_BATTLE_AXE                     = 121;
const int IP_CONST_FEAT_WEAPON_FOCUS_GREAT_AXE                      = 122;
const int IP_CONST_FEAT_WEAPON_FOCUS_HALBERD                        = 123;
const int IP_CONST_FEAT_WEAPON_FOCUS_LIGHT_HAMMER                   = 124;
const int IP_CONST_FEAT_WEAPON_FOCUS_LIGHT_FLAIL                    = 125;
const int IP_CONST_FEAT_WEAPON_FOCUS_WAR_HAMMER                     = 126;
const int IP_CONST_FEAT_WEAPON_FOCUS_HEAVY_FLAIL                    = 127;
const int IP_CONST_FEAT_WEAPON_FOCUS_KAMA                           = 128;
const int IP_CONST_FEAT_WEAPON_FOCUS_KUKRI                          = 129;
const int IP_CONST_FEAT_WEAPON_FOCUS_SHURIKEN                       = 130;
const int IP_CONST_FEAT_WEAPON_FOCUS_SCYTHE                         = 131;
const int IP_CONST_FEAT_WEAPON_FOCUS_KATANA                         = 132;
const int IP_CONST_FEAT_WEAPON_FOCUS_BASTARD_SWORD                  = 133;
const int IP_CONST_FEAT_WEAPON_FOCUS_DIRE_MACE                      = 134;
const int IP_CONST_FEAT_WEAPON_FOCUS_DOUBLE_AXE                     = 135;
const int IP_CONST_FEAT_WEAPON_FOCUS_TWO_BLADED_SWORD               = 136;
const int IP_CONST_FEAT_WEAPON_FOCUS_DWAXE                          = 137;
const int IP_CONST_FEAT_WEAPON_FOCUS_WHIP                           = 138;
const int IP_CONST_FEAT_WEAPON_FOCUS_MINDBLADE                      = 139;
const int IP_CONST_FEAT_WEAPON_FOCUS_RAY                            = 140;

const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_CLUB                  = 16000;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_DAGGER                = 16001;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_DART                  = 16002;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_HEAVY_CROSSBOW        = 16003;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_LIGHT_CROSSBOW        = 16004;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_LIGHT_MACE            = 16005;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_MORNING_STAR          = 16006;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_STAFF                 = 16007;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SPEAR                 = 16008;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SICKLE                = 16009;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SLING                 = 16010;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_UNARMED_STRIKE        = 16011;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_LONGBOW               = 16012;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SHORTBOW              = 16013;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SHORT_SWORD           = 16014;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_RAPIER                = 16015;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SCIMITAR              = 16016;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_LONG_SWORD            = 16017;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_GREAT_SWORD           = 16018;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_HAND_AXE              = 16019;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_THROWING_AXE          = 16020;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_BATTLE_AXE            = 16021;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_GREAT_AXE             = 16022;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_HALBERD               = 16023;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_LIGHT_HAMMER          = 16024;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_LIGHT_FLAIL           = 16025;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_WAR_HAMMER            = 16026;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_HEAVY_FLAIL           = 16027;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_KAMA                  = 16028;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_KUKRI                 = 16029;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SHURIKEN              = 16030;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_SCYTHE                = 16031;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_KATANA                = 16032;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_BASTARD_SWORD         = 16033;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_DIRE_MACE             = 16034;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_DOUBLE_AXE            = 16035;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_TWO_BLADED_SWORD      = 16036;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_DWAXE                 = 16037;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_WHIP                  = 16038;
const int IP_CONST_FEAT_WEAPON_SPECIALIZATION_MINDBLADE             = 16039;

const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_CLUB              = 16050;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_DAGGER            = 16051;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_DART              = 16052;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_HEAVYCROSSBOW     = 16053;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTCROSSBOW     = 16054;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTMACE         = 16055;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_MORNINGSTAR       = 16056;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_QUARTERSTAFF      = 16057;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SHORTSPEAR        = 16058;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SICKLE            = 16059;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SLING             = 16060;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_UNARMED           = 16061;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_LONGBOW           = 16062;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SHORTBOW          = 16063;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SHORTSWORD        = 16064;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_RAPIER            = 16065;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SCIMITAR          = 16066;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_LONGSWORD         = 16067;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_GREATSWORD        = 16068;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_HANDAXE           = 16069;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_THROWINGAXE       = 16070;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_BATTLEAXE         = 16071;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_GREATAXE          = 16072;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_HALBERD           = 16073;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTHAMMER       = 16074;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTFLAIL        = 16075;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_WARHAMMER         = 16076;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_HEAVYFLAIL        = 16077;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_KAMA              = 16078;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_KUKRI             = 16079;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SHURIKEN          = 16080;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_SCYTHE            = 16081;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_KATANA            = 16082;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_BASTARDSWORD      = 16083;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_DIREMACE          = 16084;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_DOUBLEAXE         = 16085;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_TWOBLADEDSWORD    = 16086;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_DWAXE             = 16087;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_WHIP              = 16088;
const int IP_CONST_FEAT_EPIC_DEVASTATING_CRITICAL_MINDBLADE         = 16089;

const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_CLUB                      = 16100;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_DAGGER                    = 16101;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_DART                      = 16102;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_HEAVY_CROSSBOW            = 16103;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_LIGHT_CROSSBOW            = 16104;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_LIGHT_MACE                = 16105;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_MORNING_STAR              = 16106;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_STAFF                     = 16107;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SPEAR                     = 16108;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SICKLE                    = 16109;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SLING                     = 16110;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_UNARMED_STRIKE            = 16111;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_LONGBOW                   = 16112;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SHORTBOW                  = 16113;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SHORT_SWORD               = 16114;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_RAPIER                    = 16115;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SCIMITAR                  = 16116;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_LONG_SWORD                = 16117;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_GREAT_SWORD               = 16118;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_HAND_AXE                  = 16119;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_THROWING_AXE              = 16120;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_BATTLE_AXE                = 16121;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_GREAT_AXE                 = 16122;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_HALBERD                   = 16123;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_LIGHT_HAMMER              = 16124;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_LIGHT_FLAIL               = 16125;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_WAR_HAMMER                = 16126;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_HEAVY_FLAIL               = 16127;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_KAMA                      = 16128;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_KUKRI                     = 16129;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SHURIKEN                  = 16130;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_SCYTHE                    = 16131;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_KATANA                    = 16132;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_BASTARD_SWORD             = 16133;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_DIRE_MACE                 = 16134;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_DOUBLE_AXE                = 16135;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_TWO_BLADED_SWORD          = 16136;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_DWAXE                     = 16137;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_WHIP                      = 16138;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_MINDBLADE                 = 16139;
const int IP_CONST_FEAT_EPIC_WEAPON_FOCUS_RAY                       = 16140;

const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_CLUB             = 16150;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_DAGGER           = 16151;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_DART             = 16152;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVY_CROSSBOW   = 16153;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHT_CROSSBOW   = 16154;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHT_MACE       = 16155;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_MORNING_STAR     = 16156;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_STAFF            = 16157;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SPEAR            = 16158;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SICKLE           = 16159;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SLING            = 16160;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_UNARMED_STRIKE   = 16161;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_LONGBOW          = 16162;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SHORTBOW         = 16163;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SHORT_SWORD      = 16164;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_RAPIER           = 16165;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SCIMITAR         = 16166;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_LONG_SWORD       = 16167;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_GREAT_SWORD      = 16168;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_HAND_AXE         = 16169;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_THROWING_AXE     = 16170;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_BATTLE_AXE       = 16171;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_GREAT_AXE        = 16172;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_HALBERD          = 16173;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHT_HAMMER     = 16174;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_LIGHT_FLAIL      = 16175;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_WAR_HAMMER       = 16176;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_HEAVY_FLAIL      = 16177;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_KAMA             = 16178;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_KUKRI            = 16179;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SHURIKEN         = 16180;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_SCYTHE           = 16181;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_KATANA           = 16182;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_BASTARD_SWORD    = 16183;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_DIRE_MACE        = 16184;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_DOUBLE_AXE       = 16185;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_TWO_BLADED_SWORD = 16186;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_DWAXE            = 16187;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_WHIP             = 16188;
const int IP_CONST_FEAT_EPIC_WEAPON_SPECIALIZATION_MINDBLADE        = 16189;

const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_CLUB             = 16200;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_DAGGER           = 16201;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_DART             = 16202;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_HEAVYCROSSBOW    = 16203;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTCROSSBOW    = 16204;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTMACE        = 16205;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_MORNINGSTAR      = 16206;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_QUARTERSTAFF     = 16207;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SHORTSPEAR       = 16208;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SICKLE           = 16209;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SLING            = 16210;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_UNARMED          = 16211;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_LONGBOW          = 16212;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SHORTBOW         = 16213;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SHORTSWORD       = 16214;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_RAPIER           = 16215;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SCIMITAR         = 16216;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_LONGSWORD        = 16217;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_GREATSWORD       = 16218;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_HANDAXE          = 16219;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_THROWINGAXE      = 16220;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_BATTLEAXE        = 16221;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_GREATAXE         = 16222;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_HALBERD          = 16223;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTHAMMER      = 16224;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_LIGHTFLAIL       = 16225;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_WARHAMMER        = 16226;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_HEAVYFLAIL       = 16227;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_KAMA             = 16228;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_KUKRI            = 16229;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SHURIKEN         = 16230;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_SCYTHE           = 16231;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_KATANA           = 16232;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_BASTARDSWORD     = 16233;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_DIREMACE         = 16234;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_DOUBLEAXE        = 16235;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_TWOBLADEDSWORD   = 16236;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_DWAXE            = 16237;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_WHIP             = 16238;
const int IP_CONST_FEAT_EPIC_OVERWHELMING_CRITICAL_MINDBLADE        = 16239;

const int IP_CONST_FEAT_WEAPON_OF_CHOICE_SICKLE                     = 16250;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_KAMA                       = 16251;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_KUKRI                      = 16252;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_CLUB                       = 16253;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_DAGGER                     = 16254;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_LIGHTMACE                  = 16255;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_MORNINGSTAR                = 16256;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_QUARTERSTAFF               = 16257;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_SHORTSPEAR                 = 16258;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_SHORTSWORD                 = 16259;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_RAPIER                     = 16260;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_SCIMITAR                   = 16261;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_LONGSWORD                  = 16262;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_GREATSWORD                 = 16263;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_HANDAXE                    = 16264;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_BATTLEAXE                  = 16265;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_GREATAXE                   = 16266;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_HALBERD                    = 16267;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_LIGHTHAMMER                = 16268;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_LIGHTFLAIL                 = 16269;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_WARHAMMER                  = 16270;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_HEAVYFLAIL                 = 16271;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_SCYTHE                     = 16272;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_KATANA                     = 16273;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_BASTARDSWORD               = 16274;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_DIREMACE                   = 16275;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_DOUBLEAXE                  = 16276;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_TWOBLADEDSWORD             = 16277;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_DWAXE                      = 16278;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_WHIP                       = 16279;
const int IP_CONST_FEAT_WEAPON_OF_CHOICE_MINDBLADE                  = 16280;

const int IP_CONST_FEAT_SUPERIOR_WEAPON_FOCUS                       = 24811;
const int IP_CONST_FEAT_EPIC_SUPERIOR_WEAPON_FOCUS                  = 24812;

// Arcane Archer
const int IP_CONST_FEAT_FEAT_PRESTIGE_IMBUE_ARROW                   = 390;

//undead feats
const int IP_CONST_FEAT_UNDEAD_HD                      = 213;
const int IP_CONST_FEAT_IMMUNITY_ABILITY_DECREASE      = 214;
const int IP_CONST_FEAT_IMMUNITY_CRITICAL              = 215;
const int IP_CONST_FEAT_IMMUNITY_DEATH                 = 216;
const int IP_CONST_FEAT_IMMUNITY_DISEASE               = 217;
const int IP_CONST_FEAT_IMMUNITY_MIND_SPELLS           = 218;
const int IP_CONST_FEAT_IMMUNITY_PARALYSIS             = 219;
const int IP_CONST_FEAT_IMMUNITY_POISON                = 220;
const int IP_CONST_FEAT_IMMUNITY_SNEAKATTACK           = 221;


// IP_CONST_CASTSPELL

const int IP_CONST_CASTSPELL_BLESSWEAPON_10         = 13;
const int IP_CONST_CASTSPELL_MAGICWEAPON_2          = 479;
const int IP_CONST_CASTSPELL_GREATERMAGICWEAPON_10  = 511;
const int IP_CONST_CASTSPELL_GREATERMAGICWEAPON_11  = 512;
const int IP_CONST_CASTSPELL_HOLY_SWORD_15          = 473;

const int IP_CONST_CASTSPELL_GRENADE_POISONVIAL     = 1140;
const int IP_CONST_CASTSPELL_POISON_WEAPON          = 1141;
const int IP_CONST_CASTSPELL_POISON_ITEM            = 1142;
const int IP_CONST_CASTSPELL_POISON_FOOD            = 1143;
const int IP_CONST_CASTSPELL_CLEAN_POISON_OFF       = 1144;

const int IP_CONST_CASTSPELL_MINDBLADE_LUCKY        = 1171;



//  IP_CONST_ONHIT_CASTSPELL
// Note: Do not add anything to this section, since multiple onhit properties conflict with each other. Instead implement your stuff via eventhook to EVENT_ONHIT.
const int IP_CONST_ONHIT_CASTSPELL_RAVAGEGOLDENICE = 200;
const int IP_CONST_ONHIT_CASTSPELL_NIGHTSHADEPOISON = 201;
const int IP_CONST_ONHIT_CASTSPELL_LINGDMG = 202;
const int IP_CONST_CASTSPELL_ELDRITCH_GLAIVE_ONHIT  = 205;

//  IP_CONST_DAMAGEBONUS

const int IP_CONST_DAMAGEBONUS_11               = 21;
const int IP_CONST_DAMAGEBONUS_12               = 22;
const int IP_CONST_DAMAGEBONUS_13               = 23;
const int IP_CONST_DAMAGEBONUS_14               = 24;
const int IP_CONST_DAMAGEBONUS_15               = 25;
const int IP_CONST_DAMAGEBONUS_16               = 26;
const int IP_CONST_DAMAGEBONUS_17               = 27;
const int IP_CONST_DAMAGEBONUS_18               = 28;
const int IP_CONST_DAMAGEBONUS_19               = 29;
const int IP_CONST_DAMAGEBONUS_20               = 30;
const int IP_CONST_DAMAGEBONUS_3d6              = 31;
const int IP_CONST_DAMAGEBONUS_4d6              = 32;
const int IP_CONST_DAMAGEBONUS_5d6              = 33;
const int IP_CONST_DAMAGEBONUS_6d6              = 34;
const int IP_CONST_DAMAGEBONUS_7d6              = 35;
const int IP_CONST_DAMAGEBONUS_8d6              = 36;
const int IP_CONST_DAMAGEBONUS_3d4              = 37;
const int IP_CONST_DAMAGEBONUS_4d4              = 38;
const int IP_CONST_DAMAGEBONUS_5d4              = 39;
const int IP_CONST_DAMAGEBONUS_6d4              = 40;
const int IP_CONST_DAMAGEBONUS_3d8              = 41;
const int IP_CONST_DAMAGEBONUS_4d8              = 42;
const int IP_CONST_DAMAGEBONUS_5d8              = 43;
const int IP_CONST_DAMAGEBONUS_6d8              = 44;
const int IP_CONST_DAMAGEBONUS_7d8              = 45;
const int IP_CONST_DAMAGEBONUS_8d8              = 46;
const int IP_CONST_DAMAGEBONUS_9d8              = 47;
const int IP_CONST_DAMAGEBONUS_10d8             = 48;
const int IP_CONST_DAMAGEBONUS_7d4              = 49;
const int IP_CONST_DAMAGEBONUS_8d4              = 50;
const int IP_CONST_DAMAGEBONUS_9d4              = 51;
const int IP_CONST_DAMAGEBONUS_10d4             = 52;
const int IP_CONST_DAMAGEBONUS_9d6              = 53;
const int IP_CONST_DAMAGEBONUS_10d6             = 54;
const int IP_CONST_DAMAGEBONUS_3d10             = 55;
const int IP_CONST_DAMAGEBONUS_4d10             = 56;
const int IP_CONST_DAMAGEBONUS_5d10             = 57;
const int IP_CONST_DAMAGEBONUS_6d10             = 58;
const int IP_CONST_DAMAGEBONUS_7d10             = 59;
const int IP_CONST_DAMAGEBONUS_8d10             = 60;
const int IP_CONST_DAMAGEBONUS_9d10             = 61;
const int IP_CONST_DAMAGEBONUS_10d10            = 62;
const int IP_CONST_DAMAGEBONUS_3d12             = 63;
const int IP_CONST_DAMAGEBONUS_4d12             = 64;
const int IP_CONST_DAMAGEBONUS_5d12             = 65;
const int IP_CONST_DAMAGEBONUS_6d12             = 66;
const int IP_CONST_DAMAGEBONUS_7d12             = 67;
const int IP_CONST_DAMAGEBONUS_8d12             = 68;
const int IP_CONST_DAMAGEBONUS_9d12             = 69;
const int IP_CONST_DAMAGEBONUS_10d12            = 70;

// IP_CONST_IMMUNITYSPELL

const int IP_CONST_IMMUNITYSPELL_BOLT_WEB     =  239;
const int IP_CONST_IMMUNITYSPELL_SHADOW_WEB   =  240;
const int IP_CONST_IMMUNITYSPELL_BELETITH_WEB =  241;
const int IP_CONST_IMMUNITYSPELL_NS_WEB       =  242;

// IP_CONST_ONHIT_SAVEDC

const int IP_CONST_ONHIT_SAVEDC_17 = 17;
const int IP_CONST_ONHIT_SAVEDC_19 = 19;

// Creature Epic Criticals
const int IP_CONST_FEAT_DEVCRITICAL_CREATURE    = 271;
const int IP_CONST_FEAT_OVERCRITICAL_CREATURE   = 272;
//const int IP_CONST_FEAT_WEAPON_PROF_CREATURE    = 38;    // provided by Bioware in 1.66

// Epic DR
const int IP_CONST_FEAT_EPIC_DR_3             = 273;
const int IP_CONST_FEAT_EPIC_DR_6             = 274;
const int IP_CONST_FEAT_EPIC_DR_9             = 275;

//IP_CONST_DAMAGETYPE
const int IP_CONST_DAMAGETYPE_VILE            = 14;

//IP_CONST_DAMAGESOAK
const int IP_CONST_DAMAGESOAK_1_HP = 11;
const int IP_CONST_DAMAGESOAK_2_HP = 12;
const int IP_CONST_DAMAGESOAK_3_HP = 13;
const int IP_CONST_DAMAGESOAK_4_HP = 14;
const int IP_CONST_DAMAGESOAK_6_HP = 15;
const int IP_CONST_DAMAGESOAK_7_HP = 16;
const int IP_CONST_DAMAGESOAK_8_HP = 17;
const int IP_CONST_DAMAGESOAK_9_HP = 18;
const int IP_CONST_DAMAGESOAK_11_HP = 19;
const int IP_CONST_DAMAGESOAK_12_HP = 20;
const int IP_CONST_DAMAGESOAK_13_HP = 21;
const int IP_CONST_DAMAGESOAK_14_HP = 22;
const int IP_CONST_DAMAGESOAK_16_HP = 23;
const int IP_CONST_DAMAGESOAK_17_HP = 24;
const int IP_CONST_DAMAGESOAK_18_HP = 25;
const int IP_CONST_DAMAGESOAK_19_HP = 26;
const int IP_CONST_DAMAGESOAK_21_HP = 27;
const int IP_CONST_DAMAGESOAK_22_HP = 28;
const int IP_CONST_DAMAGESOAK_23_HP = 29;
const int IP_CONST_DAMAGESOAK_24_HP = 30;
const int IP_CONST_DAMAGESOAK_26_HP = 31;
const int IP_CONST_DAMAGESOAK_27_HP = 32;
const int IP_CONST_DAMAGESOAK_28_HP = 33;
const int IP_CONST_DAMAGESOAK_29_HP = 34;
const int IP_CONST_DAMAGESOAK_31_HP = 35;
const int IP_CONST_DAMAGESOAK_32_HP = 36;
const int IP_CONST_DAMAGESOAK_33_HP = 37;
const int IP_CONST_DAMAGESOAK_34_HP = 38;
const int IP_CONST_DAMAGESOAK_36_HP = 39;
const int IP_CONST_DAMAGESOAK_37_HP = 40;
const int IP_CONST_DAMAGESOAK_38_HP = 41;
const int IP_CONST_DAMAGESOAK_39_HP = 42;
const int IP_CONST_DAMAGESOAK_41_HP = 43;
const int IP_CONST_DAMAGESOAK_42_HP = 44;
const int IP_CONST_DAMAGESOAK_43_HP = 45;
const int IP_CONST_DAMAGESOAK_44_HP = 46;
const int IP_CONST_DAMAGESOAK_46_HP = 47;
const int IP_CONST_DAMAGESOAK_47_HP = 48;
const int IP_CONST_DAMAGESOAK_48_HP = 49;
const int IP_CONST_DAMAGESOAK_49_HP = 50;

//IP_CONST_DAMAGERESIST
const int IP_CONST_DAMAGERESIST_500 = 20; // immunity alternative
const int IP_CONST_DAMAGERESIST_1 = 21;
const int IP_CONST_DAMAGERESIST_2 = 22;
const int IP_CONST_DAMAGERESIST_3 = 23;
const int IP_CONST_DAMAGERESIST_4 = 24;
const int IP_CONST_DAMAGERESIST_6 = 25;
const int IP_CONST_DAMAGERESIST_7 = 26;
const int IP_CONST_DAMAGERESIST_8 = 27;
const int IP_CONST_DAMAGERESIST_9 = 28;

const int IP_CONST_FEAT_SHADOWMASTER_SHADES = 141;

//IP_CONST_REDUCEDWEIGHT
const int IP_CONST_REDUCEDWEIGHT_50_PERCENT = 6;

// IP_CONST_MONSTERDAMAGE
const int IP_CONST_MONSTERDAMAGE_7d4 = 58;

//ACP feat
const int IP_CONST_ACP_FEAT = 98;

// Improved Combat Casting
const int IP_CONST_IMP_CC = 97;

// Cast Bonus Domain Radial Feats
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_ONE       = 142;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_TWO       = 143;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_THREE     = 144;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_FOUR      = 145;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_FIVE      = 146;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_SIX       = 147;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_SEVEN     = 148;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_EIGHT     = 149;
const int IP_CONST_FEAT_CAST_DOMAIN_LEVEL_NINE      = 150;
const int IP_CONST_FEAT_CHECK_DOMAIN_SLOTS      = 151;

// Bonus Domain Power Feats
const int IP_CONST_FEAT_WAR_DOMAIN              =  152;
const int IP_CONST_FEAT_STRENGTH_DOMAIN         =  153;
const int IP_CONST_FEAT_PROTECTION_DOMAIN       =  154;
const int IP_CONST_FEAT_LUCK_DOMAIN             =  155;
const int IP_CONST_FEAT_DEATH_DOMAIN            =  156;
const int IP_CONST_FEAT_AIR_DOMAIN              =  157;
const int IP_CONST_FEAT_ANIMAL_DOMAIN           =  158;
const int IP_CONST_FEAT_DESTRUCTION_DOMAIN      =  159;
const int IP_CONST_FEAT_EARTH_DOMAIN            =  160;
const int IP_CONST_FEAT_EVIL_DOMAIN             =  161;
const int IP_CONST_FEAT_FIRE_DOMAIN             =  162;
const int IP_CONST_FEAT_GOOD_DOMAIN             =  163;
const int IP_CONST_FEAT_HEALING_DOMAIN          =  164;
const int IP_CONST_FEAT_KNOWLEDGE_DOMAIN        =  165;
const int IP_CONST_FEAT_MAGIC_DOMAIN            =  166;
const int IP_CONST_FEAT_PLANT_DOMAIN            =  167;
const int IP_CONST_FEAT_SUN_DOMAIN              =  168;
const int IP_CONST_FEAT_TRAVEL_DOMAIN           =  169;
const int IP_CONST_FEAT_TRICKERY_DOMAIN         =  170;
const int IP_CONST_FEAT_WATER_DOMAIN            =  171;
const int IP_CONST_FEAT_DARKNESS_DOMAIN         =  172;
const int IP_CONST_FEAT_METAL_DOMAIN            =  173;
const int IP_CONST_FEAT_STORM_DOMAIN            =  174;
const int IP_CONST_FEAT_PORTAL_DOMAIN           =  175;
const int IP_CONST_FEAT_DWARF_DOMAIN            =  176;
const int IP_CONST_FEAT_ORC_DOMAIN              =  177;
const int IP_CONST_FEAT_FORCE_DOMAIN            =  178;
const int IP_CONST_FEAT_SLIME_DOMAIN            =  179;
const int IP_CONST_FEAT_TIME_DOMAIN             =  180;
const int IP_CONST_FEAT_CHARM_DOMAIN            =  181;
const int IP_CONST_FEAT_SPELLS_DOMAIN           =  182;
const int IP_CONST_FEAT_RUNE_DOMAIN             =  183;
const int IP_CONST_FEAT_FATE_DOMAIN             =  184;
const int IP_CONST_FEAT_DOMINATION_DOMAIN       =  185;
const int IP_CONST_FEAT_UNDEATH_DOMAIN          =  186;
const int IP_CONST_FEAT_FAMILY_DOMAIN           =  187;
const int IP_CONST_FEAT_HALFLING_DOMAIN         =  188;
const int IP_CONST_FEAT_ILLUSION_DOMAIN         =  189;
const int IP_CONST_FEAT_HATRED_DOMAIN           =  190;
const int IP_CONST_FEAT_NOBILITY_DOMAIN         =  191;
const int IP_CONST_FEAT_RETRIBUTION_DOMAIN      =  192;
const int IP_CONST_FEAT_SCALEYKIND_DOMAIN       =  193;
const int IP_CONST_FEAT_GNOME_DOMAIN            =  194;
const int IP_CONST_FEAT_ELF_DOMAIN              =  195;
const int IP_CONST_FEAT_RENEWAL_DOMAIN          =  196;
const int IP_CONST_FEAT_SPIDER_DOMAIN           =  197;
const int IP_CONST_FEAT_TYRANNY_DOMAIN          =  198;
const int IP_CONST_FEAT_OCEAN_DOMAIN            =  199;
const int IP_CONST_FEAT_BLIGHTBRINGER           =  200;
const int IP_CONST_FEAT_DRAGON_DOMAIN           =  397;

// Domain Feats
const int IP_CONST_FEAT_GREAT_FORTITUDE         =  202;
const int IP_CONST_FEAT_SCRIBE_SCROLL           =  203;


// Lasher
const int IP_CONST_FEAT_IMPROVED_KNOCKDOWN      = 264;
const int IP_CONST_FEAT_IMPROVED_DISARM         = 265;

// Spellfire
const int IP_CONST_FEAT_SPELLFIRE_INCREASE      =  266;
const int IP_CONST_FEAT_SPELLFIRE_DECREASE      =  267;
const int IP_CONST_FEAT_SPELLFIRE_QUICKSELECT   =  268;

//RotD & Dragon Magic
const int IP_CONST_FEAT_DRAGON                  = 396;
const int IP_CONST_FEAT_DRAGON_IMMUNE           = 395;
const int IP_CONST_FEAT_TOUGHNESS               = 394;
const int IP_CONST_FEAT_DRACONIC_GRACE_1_5      = 223;
const int IP_CONST_FEAT_DRACONIC_GRACE_6_9      = 224;
const int IP_CONST_FEAT_DRACONIC_BREATH_1_5     = 225;
const int IP_CONST_FEAT_DRACONIC_BREATH_6_9     = 226;

//Draconic Auras
const int IP_CONST_FEAT_BONUS_AURA_1            = 15980;
const int IP_CONST_FEAT_BONUS_AURA_2            = 15981;
const int IP_CONST_FEAT_BONUS_AURA_3            = 15982;
const int IP_CONST_FEAT_BONUS_AURA_4            = 15983;
const int IP_CONST_FEAT_2ND_AURA_POWER          = 15984;
const int IP_CONST_FEAT_2ND_AURA_ENERGYSHLD     = 15985;
const int IP_CONST_FEAT_2ND_AURA_TOUGHNESS      = 15986;
const int IP_CONST_FEAT_2ND_AURA_SENSES         = 15987;
const int IP_CONST_FEAT_2ND_AURA_VIGOR          = 15988;
const int IP_CONST_FEAT_2ND_AURA_RESISTANCE     = 15989;
const int IP_CONST_FEAT_2ND_AURA_PRESENCE       = 15990;
const int IP_CONST_FEAT_2ND_AURA_INSIGHT        = 15991;
const int IP_CONST_FEAT_2ND_AURA_RESOLVE        = 15992;
const int IP_CONST_FEAT_2ND_AURA_STAMINA        = 15993;
const int IP_CONST_FEAT_2ND_AURA_SWIFTNESS      = 15994;
const int IP_CONST_FEAT_2ND_AURA_RESISTACID     = 15995;
const int IP_CONST_FEAT_2ND_AURA_RESISTCOLD     = 15996;
const int IP_CONST_FEAT_2ND_AURA_RESISTELEC     = 15997;
const int IP_CONST_FEAT_2ND_AURA_RESISTFIRE     = 15998;
const int IP_CONST_FEAT_2ND_AURA_MAGICPOWER     = 15999;
const int IP_CONST_FEAT_2ND_AURA_ENERGYACID     = 15975;
const int IP_CONST_FEAT_2ND_AURA_ENERGYCOLD     = 15976;
const int IP_CONST_FEAT_2ND_AURA_ENERGYELEC     = 15977;
const int IP_CONST_FEAT_2ND_AURA_ENERGYFIRE     = 15978;
const int IP_CONST_FEAT_2ND_AURA_ENERGY         = 15979;

// Status markers
const int IP_CONST_FEAT_INCORPOREAL             = 227;
const int IP_CONST_FEAT_ETHEREAL                = 228;

//Racial feats
const int IP_CONST_FEAT_CRAFTGUILD              = 4987;
const int IP_CONST_FEAT_TECHGUILD               = 4988;
const int IP_CONST_FEAT_SAGEGUILD               = 4989;
const int IP_CONST_FEAT_REMAIN_CONCIOUS         = 269;
const int IP_CONST_FEAT_SHIFTER_BEASTHIDE       = 4993;
const int IP_CONST_FEAT_SHIFTER_DREAMSIGHT      = 4994;
const int IP_CONST_FEAT_SHIFTER_GOREBRUTE       = 4995;
const int IP_CONST_FEAT_SHIFTER_LONGSTRIDE      = 4996;
const int IP_CONST_FEAT_SHIFTER_LONGTOOTH       = 4997;
const int IP_CONST_FEAT_SHIFTER_RAZORCLAW       = 4998;
const int IP_CONST_FEAT_SHIFTER_WILDHUNT        = 4999;
const int IP_CONST_FEAT_TRACKLESS_STEP          = 393;
const int IP_CONST_FEAT_SEA_FOLK                = 4990;
const int IP_CONST_FEAT_RIVER_FOLK              = 4991;
const int IP_CONST_FEAT_BAMBOO_FOLK             = 4992;

// Template Feats
const int IP_CONST_FEAT_TEMPLATE_CELESTIAL_SMITE_EVIL = 16301;
const int IP_CONST_FEAT_TEMPLATE_CELESTIAL_MARKER     = 16302;
const int IP_CONST_FEAT_TEMPLATE_FIENDISH_SMITE_GOOD  = 16303;
const int IP_CONST_FEAT_TEMPLATE_FIENDISH_MARKER      = 16304;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_SMITE_EVIL   = 16305;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_PROTECTION   = 16306;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_BLESS        = 16307;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_AID          = 16308;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_DETECT       = 16309;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_CURE_SERIOUS = 16310;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_NEUTRALIZE_POISON = 16311;
//const int IP_CONST_FEAT_TEMPLATE_FIENDISH_MARKER             = 16312;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_REMOVE_DISEASE= 16313;
//const int IP_CONST_FEAT_TEMPLATE_FIENDISH_MARKER             = 16314;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_HOLY_WORD    = 16315;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_HOLY_AURA    = 16316;
//const int IP_CONST_FEAT_TEMPLATE_FIENDISH_MARKER             = 16317;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_MASS_CHARM   = 16318;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_SUMMON_IX    = 16319;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_RESURRECTION = 16320;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_DAYLIGHT     = 16321;
const int IP_CONST_FEAT_TEMPLATE_HALF_CELESTIAL_MARKER       = 16322;
const int IP_CONST_FEAT_TEMPLATE_NECROPOLITAN_MARKER         = 16323;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_SMITE_GOOD    = 16324;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_DARKNESS      = 16325;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_DESECRATE     = 16326;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_UNHOLY_BLIGHT = 16327;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_POISON        = 16328;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_CONTAGION     = 16329;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_BLASPHEMY     = 16330;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_UNHOLY_AURA   = 16331;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_UNHALLOW      = 16332;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_HORRID_WILTING= 16333;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_SUMMON_IX     = 16334;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_DESTRUCTION   = 16335;
const int IP_CONST_FEAT_TEMPLATE_HALF_FIENDISH_MARKER        = 16336;
const int IP_CONST_FEAT_TEMPLATE_LICH_FEAR_AURA              = 16337;
const int IP_CONST_FEAT_TEMPLATE_LICH_PARALYZING_TOUCH       = 16338;
const int IP_CONST_FEAT_TEMPLATE_LICH_APPEARANCE             = 16339;
const int IP_CONST_FEAT_TEMPLATE_LICH_MARKER                 = 16340;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_ALTER_SELF         = 16341;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_ASTRAL_PROJECTION  = 16342;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_CREATE_GREATER_UNDEAD = 16343;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_CREATE_UNDEAD      = 16344;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_DEATH_KNELL        = 16345;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_ENERVATION         = 16346;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_GREATER_DISPEL_MAGIC = 16347;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_HARM               = 16348;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_I  = 16349;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_II = 16350;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_III = 16351;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_IV = 16352;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_V  = 16353;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_VI = 16354;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_VII = 16355;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_VIII = 16356;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_SUMMON_CREATURE_IX = 16357;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_TELEKINESIS        = 16358;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_WEIRD              = 16359;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_GREATER_PLANAR_ALLY = 16360;
const int IP_CONST_FEAT_TEMPLATE_DEMILICH_MARKER             = 16361;
const int IP_CONST_FEAT_HDRAGON_BREATHWEAPON                 = 16362;
const int IP_CONST_FEAT_HD_CHROMATICBLACK_MARKER     = 16363;
const int IP_CONST_FEAT_HD_CHROMATICBLUE_MARKER      = 16364;
const int IP_CONST_FEAT_HD_CHROMATICGREEN_MARKER     = 16365;
const int IP_CONST_FEAT_HD_CHROMATICRED_MARKER       = 16366;
const int IP_CONST_FEAT_HD_CHROMATICWHITE_MARKER     = 16367;
const int IP_CONST_FEAT_HD_GEMAMETHYST_MARKER        = 16368;
const int IP_CONST_FEAT_HD_GEMCRYSTAL_MARKER         = 16369;
const int IP_CONST_FEAT_HD_GEMEMERALD_MARKER         = 16370;
const int IP_CONST_FEAT_HD_GEMSAPPHIRE_MARKER        = 16371;
const int IP_CONST_FEAT_HD_GEMTOPAZ_MARKER           = 16372;
const int IP_CONST_FEAT_HD_LUNGCHIANGLUNG_MARKER     = 16373;
const int IP_CONST_FEAT_HD_LUNGLILUNG_MARKER         = 16374;
const int IP_CONST_FEAT_HD_LUNGLUNGWANG_MARKER       = 16375;
const int IP_CONST_FEAT_HD_LUNGPANLUNG_MARKER        = 16376;
const int IP_CONST_FEAT_HD_LUNGSHENLUNG_MARKER       = 16377;
const int IP_CONST_FEAT_HD_LUNGTIENLUNG_MARKER       = 16378;
const int IP_CONST_FEAT_HD_LUNGTUNMILUNG_MARKER      = 16379;
const int IP_CONST_FEAT_HD_METALLICBRASS_MARKER      = 16380;
const int IP_CONST_FEAT_HD_METALLICBRONZE_MARKER     = 16381;
const int IP_CONST_FEAT_HD_METALLICCOPPER_MARKER     = 16382;
const int IP_CONST_FEAT_HD_METALLICGOLD_MARKER       = 16383;
const int IP_CONST_FEAT_HD_METALLICSILVER_MARKER     = 16384;
const int IP_CONST_FEAT_HD_OBSCUREBATTLE_MARKER      = 16385;
const int IP_CONST_FEAT_HD_OBSCUREBROWN_MARKER       = 16386;
const int IP_CONST_FEAT_HD_OBSCURECHAOS_MARKER       = 16387;
const int IP_CONST_FEAT_HD_OBSCUREDEEP_MARKER        = 16388;
const int IP_CONST_FEAT_HD_OBSCUREETHEREAL_MARKER    = 16389;
const int IP_CONST_FEAT_HD_OBSCUREFANG_MARKER        = 16390;
const int IP_CONST_FEAT_HD_OBSCUREHOWLING_MARKER     = 16391;
const int IP_CONST_FEAT_HD_OBSCUREOCEANUS_MARKER     = 16392;
const int IP_CONST_FEAT_HD_OBSCUREPYROCLASTIC_MARKER = 16393;
const int IP_CONST_FEAT_HD_OBSCURERADIANT_MARKER     = 16394;
const int IP_CONST_FEAT_HD_OBSCURERUST_MARKER        = 16395;
const int IP_CONST_FEAT_HD_OBSCURESHADOW_MARKER      = 16396;
const int IP_CONST_FEAT_HD_OBSCURESONG_MARKER        = 16397;
const int IP_CONST_FEAT_HD_OBSCURESTYX_MARKER        = 16398;
const int IP_CONST_FEAT_HD_OBSCURETARTERIAN_MARKER   = 16399;

const int IP_CONST_FEAT_IMMUNITY_TO_SLEEP            = 16400;

// Tome of Battle
const int IP_CONST_FEAT_RISING_PHOENIX = -1;
const int IP_CONST_FEAT_UNCANNY_DODGE2 = 389;

//Alienist
const int IP_CONST_PHOBIA_ABERRATION    = 24705;
const int IP_CONST_PHOBIA_ANIMAL        = 24706;
const int IP_CONST_PHOBIA_BEAST         = 24707;
const int IP_CONST_PHOBIA_CONSTRUCT     = 24708;
const int IP_CONST_PHOBIA_DRAGON        = 24709;
const int IP_CONST_PHOBIA_GOBLINOID     = 24710;
const int IP_CONST_PHOBIA_MONSTROUS     = 24711;
const int IP_CONST_PHOBIA_ORC           = 24712;
const int IP_CONST_PHOBIA_REPTILIAN     = 24713;
const int IP_CONST_PHOBIA_ELEMENTAL     = 24714;
const int IP_CONST_PHOBIA_FEY           = 24715;
const int IP_CONST_PHOBIA_GIANT         = 24716;
const int IP_CONST_PHOBIA_MAGICAL_BEAST = 24717;
const int IP_CONST_PHOBIA_SHAPECHANGER  = 24718;
const int IP_CONST_PHOBIA_UNDEAD        = 24719;
const int IP_CONST_PHOBIA_VERMIN        = 24720;

//PnP Familiars
const int IP_CONST_PNP_FAMILIAR                              = 231;

// Metamagic Feat Abilities
const int IP_CONST_FEAT_EXTEND_SPELL_ABILITY                 = 4692;
const int IP_CONST_FEAT_SILENT_SPELL_ABILITY                 = 4693;
const int IP_CONST_FEAT_STILL_SPELL_ABILITY                  = 4694;
const int IP_CONST_FEAT_EMPOWER_SPELL_ABILITY                = 4695;
const int IP_CONST_FEAT_MAXIMIZE_SPELL_ABILITY               = 4696;
const int IP_CONST_FEAT_QUICKEN_SPELL_ABILITY                = 4697;
//for use with New Spellbook System
const int IP_CONST_NSB_IMP_COMBAT_CAST                       = 4688;
const int IP_CONST_NSB_AUTO_STILL                            = 4689;
const int IP_CONST_NSB_AUTO_QUICKEN                          = 4690;
const int IP_CONST_NSB_AUTO_SILENT                           = 4691;

//Sanctify Martial Strike
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SICKLE          = 24721;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_DWARVENAXE      = 24722;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_CLUB            = 24723;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_DAGGER          = 24724;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_LIGHTMACE       = 24725;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_MORNINGSTAR     = 24726;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_QUARTERSTAFF    = 24727;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SHORTSPEAR      = 24728;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SHORTSWORD      = 24729;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_RAPIER          = 24730;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SCIMITAR        = 24731;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_LONGSWORD       = 24732;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_GREATSWORD      = 24733;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_HANDAXE         = 24734;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_BATTLEAXE       = 24735;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_GREATAXE        = 24736;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_HALBERD         = 24737;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_LIGHTHAMMER     = 24738;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_LIGHTFLAIL      = 24739;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_WARHAMMER       = 24740;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_HEAVYFLAIL      = 24741;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SCYTHE          = 24742;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_KATANA          = 24743;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_BASTARDSWORD    = 24744;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_DIREMACE        = 24745;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_DOUBLEAXE       = 24746;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_TWOBLADEDSWORD  = 24747;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_KAMA            = 24748;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_KUKRI           = 24749;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_HEAVYCROSSBOW   = 24750;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_LIGHTCROSSBOW   = 24751;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SLING           = 24752;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_LONGBOW         = 24753;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SHORTBOW        = 24754;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_SHURIKEN        = 24755;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_DART            = 24756;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_WHIP            = 24757;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_TRIDENT         = 24758;
const int IP_CONST_FEAT_SANCTIFY_MARTIAL_MINDBLADE       = 24759;

//Vile Martial Strike
const int IP_CONST_FEAT_VILE_MARTIAL_CLUB                = 24760;
const int IP_CONST_FEAT_VILE_MARTIAL_DAGGER              = 24761;
const int IP_CONST_FEAT_VILE_MARTIAL_LIGHTMACE           = 24762;
const int IP_CONST_FEAT_VILE_MARTIAL_MORNINGSTAR         = 24763;
const int IP_CONST_FEAT_VILE_MARTIAL_QUARTERSTAFF        = 24764;
const int IP_CONST_FEAT_VILE_MARTIAL_SHORTSPEAR          = 24765;
const int IP_CONST_FEAT_VILE_MARTIAL_SHORTSWORD          = 24766;
const int IP_CONST_FEAT_VILE_MARTIAL_RAPIER              = 24767;
const int IP_CONST_FEAT_VILE_MARTIAL_SCIMITAR            = 24768;
const int IP_CONST_FEAT_VILE_MARTIAL_LONGSWORD           = 24769;
const int IP_CONST_FEAT_VILE_MARTIAL_GREATSWORD          = 24770;
const int IP_CONST_FEAT_VILE_MARTIAL_HANDAXE             = 24771;
const int IP_CONST_FEAT_VILE_MARTIAL_BATTLEAXE           = 24772;
const int IP_CONST_FEAT_VILE_MARTIAL_GREATAXE            = 24773;
const int IP_CONST_FEAT_VILE_MARTIAL_HALBERD             = 24774;
const int IP_CONST_FEAT_VILE_MARTIAL_LIGHTHAMMER         = 24775;
const int IP_CONST_FEAT_VILE_MARTIAL_LIGHTFLAIL          = 24776;
const int IP_CONST_FEAT_VILE_MARTIAL_WARHAMMER           = 24777;
const int IP_CONST_FEAT_VILE_MARTIAL_HEAVYFLAIL          = 24778;
const int IP_CONST_FEAT_VILE_MARTIAL_SCYTHE              = 24779;
const int IP_CONST_FEAT_VILE_MARTIAL_KATANA              = 24780;
const int IP_CONST_FEAT_VILE_MARTIAL_BASTARDSWORD        = 24781;
const int IP_CONST_FEAT_VILE_MARTIAL_DIREMACE            = 24782;
const int IP_CONST_FEAT_VILE_MARTIAL_DOUBLEAXE           = 24783;
const int IP_CONST_FEAT_VILE_MARTIAL_TWOBLADEDSWORD      = 24784;
const int IP_CONST_FEAT_VILE_MARTIAL_KAMA                = 24785;
const int IP_CONST_FEAT_VILE_MARTIAL_KUKRI               = 24786;
const int IP_CONST_FEAT_VILE_MARTIAL_HEAVYCROSSBOW       = 24787;
const int IP_CONST_FEAT_VILE_MARTIAL_LIGHTCROSSBOW       = 24788;
const int IP_CONST_FEAT_VILE_MARTIAL_SLING               = 24789;
const int IP_CONST_FEAT_VILE_MARTIAL_LONGBOW             = 24790;
const int IP_CONST_FEAT_VILE_MARTIAL_SHORTBOW            = 24791;
const int IP_CONST_FEAT_VILE_MARTIAL_SHURIKEN            = 24792;
const int IP_CONST_FEAT_VILE_MARTIAL_DART                = 24793;
const int IP_CONST_FEAT_VILE_MARTIAL_SICKLE              = 24794;
const int IP_CONST_FEAT_VILE_MARTIAL_DWARVENAXE          = 24795;
const int IP_CONST_FEAT_VILE_MARTIAL_WHIP                = 24796;
const int IP_CONST_FEAT_VILE_MARTIAL_TRIDENT             = 24797;
const int IP_CONST_FEAT_VILE_MARTIAL_MINDBLADE           = 24898;

//Epic Dodge, Epic Prowess
const int IP_CONST_FEAT_EPIC_DODGE = 24799;
const int IP_CONST_FEAT_EPIC_PROWESS = 24810;

//Epic Toughness
const int IP_CONST_FEAT_EPIC_TOUGHNESS_1           = 24800;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_2           = 24801;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_3           = 24802;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_4           = 24803;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_5           = 24804;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_6           = 24805;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_7           = 24806;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_8           = 24807;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_9           = 24808;
const int IP_CONST_FEAT_EPIC_TOUGHNESS_10          = 24809;
