// prc_onrespawn,js_util_onrespwn
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrespawn event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onrespawn", OBJECT_SELF);
    ExecuteScript("js_util_onrespwn", OBJECT_SELF);
}
