// prc_ondying,js_util_ondying
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdying event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_ondying", OBJECT_SELF);
    ExecuteScript("js_util_ondying", OBJECT_SELF);
}
