// prc_onactivate,wk_activate
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onactivateitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onactivate", OBJECT_SELF);
    ExecuteScript("wk_activate", OBJECT_SELF);
}
