// prc_equip,cw_mod_onequip
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerequipitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_equip", OBJECT_SELF);
    ExecuteScript("cw_mod_onequip", OBJECT_SELF);
}
