// prc_ondeath,ith_on_death
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerdeath event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_ondeath", OBJECT_SELF);
    ExecuteScript("ith_on_death", OBJECT_SELF);
}
