// prc_rest,z_mod_0nrest
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerrest event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_rest", OBJECT_SELF);
    ExecuteScript("z_mod_0nrest", OBJECT_SELF);
}
