// prc_levelup,chk_currentclass
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onplayerlevelup event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_levelup", OBJECT_SELF);
    ExecuteScript("chk_currentclass", OBJECT_SELF);
}
