// prc_onaquire,wk_acquire
/////////////////////////////////////////////////////////////////////
//
// This script has been auto-generated by HakInstaller to call
// multiple handlers for the onacquireitem event.
//
/////////////////////////////////////////////////////////////////////

void main()
{
    ExecuteScript("prc_onaquire", OBJECT_SELF);
    ExecuteScript("wk_acquire", OBJECT_SELF);
}
