/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.3

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

object oTarget;
oTarget = oPC;

effect eEffect;
eEffect = EffectDeath();

ApplyEffectToObject(DURATION_TYPE_PERMANENT, eEffect, oTarget);

FloatingTextStringOnCreature("You have fallen to your death!!!", oPC);

}

